---
# tasks file for apache
- name: tasks to install and configure apache
  hosts: all
  become: true
  tasks:
  - name: Ensure Apache is installed
    package: 
      name: httpd
      state: present

  - name: Copy a web page
    copy:
      content: |
        <html>
        <head><title>Hello World</title></head>
        <body>Hello World</body>
        </html>
      dest: /var/www/html/index.html
    notify: restart apache
 
  - name: Ensure Service is running
    service:
      name: httpd
      state: started
      enabled: true

  handlers:
  - name: restart apache
    service:
      name: httpd
      state: restarted

